on:
  workflow_dispatch:
  push:
    branches: deploy

name: Quarto Publish




jobs:
  build-deploy:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install curl and other non r dependencies
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev libudunits2-dev
      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      - name: Get data and Render
        run : |
          quarto render

      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
